# Generated by Django 5.0.1 on 2024-02-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deliveryrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
