# Generated by Django 5.0.1 on 2024-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("getter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="delivery_time",
            field=models.DateTimeField(),
        ),
    ]
