# Generated by Django 5.0.1 on 2024-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getter', '0002_alter_delivery_options_alter_deliveryrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
